[project]
name = "dify-plugin-linkup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dify-plugin>=0.2.1",
    "linkup-sdk>=0.2.4",
]
